travis test

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,4 +1,15 @@
 #!/usr/bin/env bash
+
+UPGRADE="0"
+while getopts ":u" opt; do
+  case $opt in
+    u) UPGRADE="1"
+    ;;
+    \?) echo "Invalid option -$OPTARG" >&2
+    ;;
+  esac
+done
+
 source functions/update.sh
 source functions/upgrade.sh
 source functions/add-repo.sh
@@ -38,7 +49,9 @@ source customs/google-apps.sh
 
 # update, upgrade, clean
 update
-upgrade
+if [[ "${UPGRADE}" = "1" ]]; then
+  upgrade
+fi
 clean
 
 echo 
